version: "3.8"
services:
    zookeeper:
      image: confluentinc/cp-zookeeper:5.0.0
      restart: always
      networks:
        - kafka-shared
      hostname: zookeeper
      container_name: zookeeper
      environment:
        ZOOKEEPER_SERVER_ID: 1
        ZOOKEEPER_CLIENT_PORT: "2181"
        ZOOKEEPER_TICK_TIME: "2000"
      ports:
        - "2181:2181"

    kafka-consumer:
      image: confluentinc/cp-enterprise-kafka:5.0.0
      hostname: kafka
      networks:
        - kafka-shared
      container_name: kafka-consumer
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
        - "29092:29092"
      environment:
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_BROKER_ID: 1
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  kafka-shared:
    name: kafka-shared
